# Generated by Django 3.2 on 2021-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeStamp',
        ),
    ]
